---
title: "Ichthyo_QAQC"
author: "Lisa Vance"
date: "2024-02-13"
output: html_document
editor_options: 
  chunk_output_type: console
---
YBFMP Ichtyoplankton Data 1998 - 2022

```{r set-options, echo=FALSE, cache=FALSE}

options(width = 10000)
```

## Setup

1. Set up and load libraries

```{r setup, results=FALSE, warning = FALSE, message = FALSE}

rm(list=ls(all=TRUE))

library(tidyverse)
library(dplyr)
library(ggplot2)
library(moderndive)
library(knitr)
library(gridExtra)
library(stringr)
library(plotly)
library(viridis)
library(kableExtra)
library(lubridate)
library(readxl)
library(readr)
library(anytime)
library(magrittr)
library(janitor)
library(tidylog)
```

2. Load data and check variable types
Note data is in both MS Access and MS Excel
Physical data is shared between drift and ichthyo since tows are done at the same time and site

```{r load, results = FALSE, warning = FALSE, message = FALSE}

################# bring in qa/qc physical data #################################
PhysData <-read_csv("drift data/LT_phys_qc_20240118.csv")

######### Read in Access catch data ###########################################

CatchData <- read_csv("ichthyo data/TblLarvalCatchDataAccess.csv")
Species <- read_csv("ichthyo data/TblLarvalLookUpV2.csv")
SamplingData <- read_csv("ichthyo data/TblLarvalSampAccess.csv")
IEPFish <- read_csv("ichthyo data/IEP FISH CODE.csv")

########## Read in Excel Catch data ###########################################

IchLabData <- read_csv("ichthyo data/IchLabExcelData.csv", skip=1)


```

3. Rename some columns
```{r filter, results = FALSE, message = FALSE, warning = FALSE}

Species <- Species %>%
  rename (SpeciesCode = "Code",
          CommonName = "Species",
          ScientificName = "Scientific Name")
View(Species)

SamplingData <- SamplingData %>%
  rename (SamplingQAQCByAccess = "QA/QC'dBy",
          SamplingEnteredByAccess = 'EnteredBy')
View(SamplingData)

IEPFish <- IEPFish %>%
  select(-c("...5":"...17"))
View(IEPFish)

```


